start_high_flow_bypass:
  fields:
    config_entry_id:
      required: false
      selector:
        text:
    duration_minutes:
      required: false
      selector:
        number:
          min: 1
          max: 1440
          step: 1
          unit_of_measurement: min

cancel_high_flow_bypass:
  fields:
    config_entry_id:
      required: false
      selector:
        text:

reset_learning:
  fields:
    config_entry_id:
      required: false
      selector:
        text:
