name: Hassfest

on:
  workflow_dispatch:
  push:
    branches:
      - rename-water-guard

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: home-assistant/actions/hassfest@master
        continue-on-error: true
