name: Temporary HACS License Recheck

on:
  push:
    branches:
      - add-agpl-3-license

permissions: {}

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: integration
